from playwright.sync_api import expect
from journal.db import one

def check_editor(page,app,output):
    journal=page.locator('.journal-panel [data-md-content=body]')
    raw=page.locator('#journal-body')
    expect(journal).to_be_visible()
    page.get_by_role('button',name='Festhalten',exact=True).click()
    expect(page.locator('.journal-panel .md-invalid')).to_be_visible()
    journal.click()
    journal.press_sequentially('# Ein klarer Tag',delay=5)
    expect(page.locator('.journal-panel .md-h1')).to_have_text('Ein klarer Tag')
    journal.press('Enter')
    journal.press_sequentially('**Wichtig** und *kursiv*',delay=5)
    expect(page.locator('.journal-panel .md-bold')).to_have_text('Wichtig')
    expect(page.locator('.journal-panel .md-italic')).to_have_text('kursiv')
    original='# Ein klarer Tag\n**Wichtig** und *kursiv*'
    expect(raw).to_have_value(original)
    assert '**' not in journal.inner_text()
    journal.press('Enter')
    journal.press_sequentially('- Erster Punkt',delay=5)
    assert '•' in journal.inner_text()
    journal.press('Enter')
    journal.press_sequentially('Zweiter Punkt',delay=5)
    assert '- Zweiter Punkt' in raw.input_value()
    source=raw.input_value()
    journal.press('Control+z')
    assert raw.input_value()!=source
    journal.press('Control+y')
    expect(raw).to_have_value(source)
    journal.press('ArrowLeft')
    journal.press('ArrowRight')
    expect(raw).to_have_value(source)
    page.locator('.journal-panel').get_by_role('button',name='Markdown-Quelltext anzeigen',exact=True).click()
    assert '**Wichtig**' in journal.inner_text()
    expect(raw).to_have_value(source)
    page.locator('.journal-panel').get_by_role('button',name='Formatierten Text anzeigen',exact=True).click()
    expect(page.locator('.journal-panel .md-bold')).to_have_text('Wichtig')
    expect(raw).to_have_value(source)
    page.locator('.journal-panel').screenshot(path=str(output/'markdown-live.png'))
    page.get_by_role('button',name='Festhalten',exact=True).click()
    expect(page.locator('.journal-panel .entry-card').filter(has_text='Ein klarer Tag')).to_be_visible()
    with app.app_context():
        saved=one("SELECT body FROM entries WHERE body LIKE '# Ein klarer Tag%'")
        assert saved['body'].replace('\r\n','\n')==source
    page.locator('.topbar [data-new-entry]').click()
    dialog=page.locator('#entry-dialog')
    body=dialog.locator('[data-md-content=body]')
    expect(dialog.locator('[name=body]')).to_have_value('')
    body.click()
    body.press_sequentially('**Nicht übernehmen**',delay=3)
    dialog.get_by_role('button',name='Abbrechen',exact=True).click()
    page.locator('.topbar [data-new-entry]').click()
    expect(dialog.locator('[name=body]')).to_have_value('')
    body.click();body.press('Control+z')
    expect(dialog.locator('[name=body]')).to_have_value('')
    sample='## Import\n\n| Spalte | Wert |\n| --- | --- |\n| A | B |\n\nFENCEpython\nprint("Hallo")\nFENCE\n\n<img src="https://tracking.invalid/pixel" onerror="window.BAD=1">\n\nText[^1]\n\n[^1]: Fußnote\n'.replace('FENCE',chr(96)*3)
    body.evaluate("""(element,text)=>{
      const data=new DataTransfer();data.setData('text/plain',text);
      element.dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true}));
    }""",sample)
    expect(dialog.locator('[name=body]')).to_have_value(sample)
    assert body.locator('img[src],script,[onerror]').count()==0
    assert page.evaluate('window.BAD === undefined')
    expect(dialog.locator('.md-code-line').first).to_be_visible()
    body.press('Control+End')
    body.press_sequentially('Nachtrag',delay=3)
    expect(dialog.locator('[name=body]')).to_have_value(sample+'Nachtrag')
    dialog.get_by_role('button',name='Abbrechen',exact=True).click()
