from playwright.sync_api import expect


def check_institutions(page,app,output):
    origin=page.url.split('/')[0]+'//'+page.url.split('/')[2]
    page.goto(origin+'/people')
    if page.locator('#suggestions').count() and not page.locator('#suggestions').evaluate('(el)=>el.open'): page.locator('#suggestions > summary').click()
    page.get_by_role('button',name='Neuer Kontakt',exact=True).click()
    dialog=page.locator('#person-dialog')
    dialog.locator('[name=name]').fill('Institution Browserkontakt')
    dialog.get_by_label('Rolle',exact=True).fill('Sachbearbeitung')
    dialog.get_by_label('Institution',exact=True).fill('Schulamt Browserstadt')
    dialog.get_by_role('button',name='Kontakt speichern',exact=True).click()
    expect(dialog).not_to_be_visible()
    page.get_by_label('Nach Institution filtern').select_option('Schulamt Browserstadt')
    page.get_by_role('button',name='Suchen',exact=True).click()
    cards=page.locator('.card-grid > section')
    expect(cards).to_have_count(1)
    expect(cards).to_contain_text('Institution Browserkontakt')
    expect(cards).to_contain_text('Rolle: Sachbearbeitung')
    cards.get_by_role('button',name='Bearbeiten',exact=True).click()
    expect(dialog.get_by_label('Institution',exact=True)).to_have_value('Schulamt Browserstadt')
    expect(dialog.get_by_label('Rolle',exact=True)).to_have_value('Sachbearbeitung')
    dialog.get_by_label('Rolle',exact=True).fill('Referentin')
    dialog.get_by_role('button',name='Kontakt speichern',exact=True).click()
    expect(dialog).not_to_be_visible()
    expect(cards).to_contain_text('Rolle: Referentin')
    page.set_viewport_size({'width':390,'height':844})
    assert page.evaluate('document.documentElement.scrollWidth<=window.innerWidth')
    page.screenshot(path=str(output/'institutions-mobile.png'),full_page=True)
    page.get_by_role('link',name='Filter zurücksetzen',exact=True).click()
    expect(page.get_by_label('Nach Institution filtern')).to_have_value('')
    page.set_viewport_size({'width':1440,'height':1100})
    page.goto(origin+'/')
