from playwright.sync_api import expect
from journal.db import one,rows


def check_task_groups(page,app,output):
    origin=page.url.split('/')[0]+'//'+page.url.split('/')[2]
    page.goto(origin+'/')
    page.locator('.topbar [data-new-entry]').click()
    dialog=page.locator('#entry-dialog')
    dialog.locator('[name=title]').fill('Gespräch mit mehreren Aufgaben')
    dialog.locator('[name=type]').select_option('meeting')
    dialog.locator('summary').filter(has_text='Aufgaben aus diesem Eintrag').click()
    dialog.locator('[name=new_task]').fill('Protokoll verteilen')
    dialog.get_by_role('button',name='Weitere Aufgabe',exact=True).click()
    dialog.locator('[name=new_task]').nth(1).fill('Rückmeldungen sammeln')
    dialog.locator('[name=task_due]').nth(1).fill('2026-10-01')
    dialog.get_by_role('button',name='Weitere Aufgabe',exact=True).click()
    dialog.locator('[data-remove-task]').last.click()
    expect(dialog.locator('[name=new_task]')).to_have_count(2)
    dialog.get_by_role('button',name='Eintrag speichern',exact=True).click()
    expect(dialog).not_to_be_visible()
    with app.app_context():
        eid=one("SELECT id FROM entries WHERE title='Gespräch mit mehreren Aufgaben'")['id']
        tasks=rows('SELECT * FROM tasks WHERE entry_id=? ORDER BY id',(eid,))
        assert len(tasks)==2
        tid=tasks[0]['id']
    page.goto(origin+f'/entry/{eid}')
    page.get_by_role('button',name='Eintrag bearbeiten',exact=True).click()
    expect(dialog.locator('[name=new_task]')).to_have_count(1)
    expect(dialog.locator('[name=new_task]')).to_have_value('')
    dialog.get_by_role('button',name='Abbrechen',exact=True).click()
    page.locator(f'#task-{tid}').get_by_role('button',name='Protokoll verteilen',exact=True).click()
    task=page.locator('#task-dialog')
    task.locator('summary').filter(has_text='Neue Unteraufgaben').click()
    task.locator('[name=subtask_text]').fill('Protokoll prüfen')
    task.get_by_role('button',name='Weitere Unteraufgabe',exact=True).click()
    task.locator('[name=subtask_text]').nth(1).fill('Verteiler prüfen')
    task.get_by_role('button',name='Aufgabe speichern',exact=True).click()
    expect(task).not_to_be_visible()
    parent=page.locator(f'#task-{tid}')
    expect(parent).to_contain_text('0/2 Unteraufgaben erledigt')
    parent.locator('.task-check').click()
    expect(page.locator('#toast')).to_contain_text('Bitte zuerst die offenen Unteraufgaben erledigen.')
    with app.app_context(): children=rows('SELECT id FROM tasks WHERE parent_id=? ORDER BY id',(tid,))
    for child in children:
        page.locator(f'#task-{child["id"]} .task-check').click()
        expect(parent).to_be_visible()
        expect(page.locator(f'#task-{child["id"]}')).to_have_class('task-row completed is-subtask')
    expect(parent).to_contain_text('2/2 Unteraufgaben erledigt')
    parent.locator('.task-check').click()
    expect(parent).to_have_class('task-row completed ')
    page.locator(f'#task-{children[0]["id"]} .task-check').click()
    expect(parent).not_to_have_class('task-row completed ')
    parent.locator('.task-actions > summary').click()
    parent.get_by_role('button',name='Unteraufgabe',exact=True).click()
    expect(task.locator('[data-task-heading]')).to_have_text('Neue Unteraufgabe')
    expect(task.locator('[data-subtask-section]')).not_to_be_visible()
    task.locator('[name=text]').fill('Versand bestätigen')
    task.get_by_role('button',name='Aufgabe speichern',exact=True).click()
    expect(task).not_to_be_visible()
    expect(parent).to_contain_text('1/3 Unteraufgaben erledigt')
    page.set_viewport_size({'width':390,'height':844})
    assert page.evaluate('document.documentElement.scrollWidth<=window.innerWidth')
    page.screenshot(path=str(output/'subtasks-mobile.png'),full_page=True)
    page.set_viewport_size({'width':1440,'height':1100})
    page.goto(origin+'/')
